### ISSUE TITLE
High level ideals for image server/middleware

### ISSUE THREAD

**Issue by ctolkien** [SixLabors/ImageSharp.Web#14]
This is a discussion post around features that I'd like to see long term in a Mvc Core image server/middleware. 

Currently, this project is built around a URL based API which has limitations and doesn't cover the gamut of what we need to serve the best image for a given situation:

We need different image formats based on the client `Accept` header:

- [ ] WebP - Chrome / Opera
- [ ] JpegXR - Edge
- [ ] Jpeg2000/JP2 - Safari
- [ ] Everything else

(Note that Safari does not announce support for Jpeg2000, but it is apparently supported)

We need different sizes based on the device pixel ration (`DPR`), `Viewport-Width` and intended display `Width`. These are announced with `Client Hints` on supported browsers:

- [x] Chrome
- [ ] Firefox - https://bugzilla.mozilla.org/show_bug.cgi?id=935216
- [ ] Edge - https://developer.microsoft.com/en-us/microsoft-edge/platform/status/httpclienthints/
- [ ] Safari - ?

We need to set cache headers appropriately when varying by all of these things.

We also want to simplify the amount of work we need to do to handle images in markup with Tag Helpers.

We _may_ want to add an `Accepts-CH` header to the response to indicate that we honour `Client Hints` automatically via `TagHelperComponents`.

We'd like to automatically handle `srcset` attribute generation on `img` tags.

We'd like to automatically generate markup for `picture` elements to simplify the markup generated.

Longer term, further API's are being discussed such as Network Information - this info could allow us to serve 1x images to higher DPI displays if their connection (`downlink`) appears to be poor or their `EffectiveConnectionType` is `2g` (for example).

And we also need to handle the source imagery probably not being ideal either (i.e, all the existing options for cropping a certain way, etc.)

I'm just kicking the tin can around at the moment with some ideas in my head.  Maybe this is a `SixLabors.Web` thing - maybe it's something completely different. I just wanted to open up a discussion at this stage.

All the best! ❤️

**Comment by JimBobSquarePants** [comment]
Hey @ctolkien 

You've caught me online with a little time so I'll quickly answer some of those things.

>Currently, this project is built around a URL based API which has limitations and doesn't cover the gamut of what we need to serve the best image for a given situation:

The [`IUriParser`](https://github.com/SixLabors/ImageSharp.Web/blob/b437a2c4bdb70919d598733a76b9b8d08667d7d5/src/ImageSharp.Web/Commands/IUriParser.cs) is actually pluggable and can be replaced with anything you like. It only accepts the `HttpContext` as a parameter (I could rename it to `ICommandParser).

>We need different image formats based on the client Accept header: 

The formats served depends on the formats available to ImageSharp. Writing image decoders/encoders is hard due to the cryptic nature of standards, c-based versions and ignoring of those standards (Adobe).

I have no plans to personally write any of the mentioned ones since they are not cross platform. (Plus WebP is a bit rubbish and can be matched using MozJpeg).

> We may want to add an Accepts-CH header to the response to indicate that we honour Client Hints automatically via TagHelperComponents.

The response headers can be altered already, it's in the options.

https://github.com/SixLabors/ImageSharp.Web/blob/b437a2c4bdb70919d598733a76b9b8d08667d7d5/src/ImageSharp.Web/Middleware/ImageSharpMiddlewareOptions.cs#L72

>We'd like to automatically handle srcset attribute generation on img tags.
>We'd like to automatically generate markup for picture elements to simplify the markup generated.

I've considered this but I'm thinking for now it's probably out of scope for the project. What happens when someone wants to use a custom component, or change something else?

I much prefer the idea of the API being imperative, you ask for something, you get it but don't expect us to make assumptions for you.

>Longer term, further API's are being discussed such as Network Information - this info could allow us to serve 1x images to higher DPI displays if their connection (downlink) appears to be poor or their EffectiveConnectionType is 2g (for example).

This sounds like something that would be handled via a custom [`IImageResolver`](https://github.com/SixLabors/ImageSharp.Web/blob/b437a2c4bdb70919d598733a76b9b8d08667d7d5/src/ImageSharp.Web/Resolvers/IImageResolver.cs) again, that takes a `HttpContext` as a parameter.

>And we also need to handle the source imagery probably not being ideal either (i.e, all the existing options for cropping a certain way, etc.)

All the commands for resizing an image using focal point, resize mode, etc are already available.

https://github.com/SixLabors/ImageSharp.Web/blob/b437a2c4bdb70919d598733a76b9b8d08667d7d5/src/ImageSharp.Web/Processors/ResizeWebProcessor.cs#L16

Here's my plan for ImageSharp.Web:

We build something that is extensible containing the endpoints that allow addition of all the functionality you ask for. This, we give away for free.

Anything else... Parsers, formats, processors, optimizers, etc will be available either for purchase (if built) or building by contract.  (SHOOOOOW MEEEEEE THE MONEEEEEEY!)

Does all this make sense?

Cheers

James

**Comment by JimBobSquarePants** [comment]
I'm gonna close this as it's far too broad a scope for a single issue and I believe we have now exposed all the various required endpoints to fulfill the requirements.
