### ISSUE TITLE
How to prevent rotation based on Exif Orientation

### ISSUE THREAD

**Issue by rosrosros** [SixLabors/ImageSharp.Web#258]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp.Web
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp.Web/issues) and [closed](https://github.com/SixLabors/ImageSharp.Web/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp.Web version

2.0.0.0

### Other Six Labors packages and versions

SixLabors.ImageSharp.Web.Providers.Azure 2.20.0

### Environment (Operating system, version and so on)

Windows

### .NET Framework version

6.0

### Description

When processing an image I get a rotated image more often than expected

### Steps to Reproduce

I have a jpg image that contains the exif orientation tag with the value "Rotate 90 CW"

https://site.com/img/pic.jpg -> not rotated (as expected)
https://site.com/img/pic.jpg?orient=false -> rotated (**not as expected**)
https://site.com/img/pic.jpg?orient=true -> rotated (as expected) 
https://site.com/img/pic.jpg?width=800 -> rotated (as expected)

Question 1: is this the intended behavior?
Question 2: how do I prevent rotation from happing at all?

### Images

[org_img.zip](https://github.com/SixLabors/ImageSharp.Web/files/8610697/org_img.zip)

**Comment by JimBobSquarePants** [comment]
@rosrosros I'm assuming you mist be seeing something iffy with your browser as this is all working as expected for me. 

https://site.com/img/pic.jpg -> rotated (as expected since we're not adjusting the image)
https://site.com/img/pic.jpg?orient=false -> rotated (as expected since we're not adjusting the image)
https://site.com/img/pic.jpg?orient=true -> rotated (as expected since we're not adjusting the image)
https://site.com/img/pic.jpg?width=800 -> rotated (as expected)
https://site.com/img/pic.jpg?orient=false&width=800 -> rotated but resized using swapped dimensions (as expected since we're adjusting the image)

I'm gonna close this since we cannot cater for browser issues. #260 will provide a fallback.
