### ISSUE TITLE
Full .net Framework support?

### ISSUE THREAD

**Issue by Dustymcp** [SixLabors/ImageSharp.Web#39]
### Prerequisites

Install latest Imagesharp.Web beta 0.3
reg service inside startup.cs with:
services.AddImageSharp();

### Description
Nothing happens when trying to call ?height=100 on any images from wwwroot.

### Steps to Reproduce
Download startup template for asp.net boilerplate here: https://aspnetboilerplate.com/
Set full .NET framework.
Add own connectionstring
Add nuget package imagesharp.web
Add services registration

### System Configuration
.net core 2.1
full framework 4.6.1

Im still new to Core could anyone explain to me what version i should use when using a combination of core and framework. 

Thank you for an excellent library i used imageprocessor.web quite alot, woul be very lovely to get this working with abp's new template.

**Comment by JimBobSquarePants** [comment]
Hi @Dustymcp 

Do you mean you are trying to run the middleware in System.Web.Mvc?

**Comment by Dustymcp** [comment]
Hi @JimBobSquarePants im just trying to use https://github.com/SixLabors/ImageSharp.Web inside of ABP.

I just installed the nuget package and registered services, but nothing is happening and im wondering if its because of ABP supporting full .net framework 4.6.1 but they do run all else in core, i guess im still abit confused about these concepts just messing around, any help is appreciated i understand its still beta, thank you for your time!

**Comment by JimBobSquarePants** [comment]
Hi @Dustymcp 

The reason I ask is because System.Web.Mvc doesn't use ASP.NET Core Middleware which is what this library uses. Instead it uses HttpModules to intercept requests.

Looking at the ASP.NET Boilerplate it has two entirely separate frameworks with only a little shared code.  MVC 5.x for the NET Framework and ASP.NET Core 2.x for Core

https://aspnetboilerplate.com/Templates

This would indicate to me that this library is not compatible with their NET Framework templates since it runs on an entirely different architecture. (ASP.NET Core) The developmental status of this library will not change that. 

So in order to use this library I suggest you use ASP.NET Core (Which I would recommend for all new projects anyway).

If you are stuck using the full NET Framework I would recommend using another library I wrote a few years ago called ImageProcessor.Web  

http://imageprocessor.org/imageprocessor-web/
https://www.nuget.org/packages/ImageProcessor.Web/

I hope that all makes sense,

Cheers

James

**Comment by asapostolov** [comment]
Do you have any plans to allow for .NET Framework support for `ImageSharp.Web`. I just saw that `ImageProcessor` is Archived and not maintained anymore. I have a conflict - another project updated `Microsoft.IO.RecyclableMemoryStream` to version > 3.0, so `ImageProcessor.Web` doesn't work with it anymore - it throws exception on missing methods (it expects version >1.2).

My natural inclination is to fork `ImageProcessor` and try to fix the issue and have a custom build, but I'm looking for alternatives as well.
